login: &login
  access_key_id: 
  secret_access_key: 

development:
  bucket_name: whatsthatrunning_development
  <<: *login
  distribution_domain: 

test:
  bucket_name: whatsthatrunning_test
  <<: *login
  distribution_domain: 

production:
  bucket_name: whatsthatrunning_production
  <<: *login
  distribution_domain: 
