login: &login
  adapter: mysql
  host: localhost
  username: root
  password: root

development:
  database: whatsthatrunning_development
  <<: *login

test:
  database: whatsthatrunning_test
  <<: *login

production:
  database: whatsthatrunning_production
  adapter: mysql
  host: localhost
  username: whatsthatrunning_production_login
  password: whatsthatrunning_production_password
